version: '3.4'
services:
  workflow-app: #isolate the workflow-app by removing its ports and taking it off the network
    ports: !reset 
      - "9999:9999"
    networks: !reset
      - ""
  workflow-dapr:
    image: "daprio/daprd:nightly-2023-08-12-mariner-linux-arm64"
    command: ["./daprd",
     "-app-id", "workflow",
     "-app-port", "5111",
     "-placement-host-address", "placement:50006",
     "-resources-path", "/components",
     "-app-channel-address", "host.docker.internal"] # make the sidecar look on the host for the App Channel
    network_mode: !reset "" # reset the network_mode...
    networks: # ... so that we can put the sidecar onto the normal network
      - network
    ports:
      - "3500:3500" # Expose the HTTP port to the host
      - "50001:50001" # Expose the GRPC port to the host (Dapr Worfklows depends upon the GRPC channel)