version: '3.4'
services:
  workflow-app-a: #isolate the workflow-app by removing its ports and taking it off the network
    ports: !reset []
    networks: !reset
      - ""
  workflow-dapr-a:
    command: ["./daprd",
     "-app-id", "workflow-a",
     "-app-port", "5111",
     "-placement-host-address", "placement:50006",
     "-resources-path", "/components",
     "-app-channel-address", "host.docker.internal"] # make the sidecar look on the host for the App Channel
    network_mode: !reset "" # reset the network_mode...
    networks: # ... so that the sidecar can go into the normal network
      - network
    ports:
      - "3500:3500" # Expose the HTTP port to the host
      - "50001:50001" # Expose the GRPC port to the host (Dapr Worfklows depends upon the GRPC channel)