version: '3.4'
services:
  ############################
  # Workflow App + Dapr sidecar
  ############################
  workflow-app:
    build:
      context: .
      dockerfile: Workflow/Dockerfile
    ports:
      - "5111:5111"
      - "3500:3500"
    depends_on:
      - redis
      - placement
    networks:
      - network
  workflow-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd",
     "-app-id", "workflow",
     "-app-port", "5111",
     "-dapr-http-port", "3500",
     "-placement-host-address", "placement:50006",
     "-dapr-grpc-port", "4001",
     "-components-path", "/components",
     "-log-level","debug"]
    volumes:
        - "./components/:/components"
    depends_on:
      - workflow-app
    network_mode: "service:workflow-app"
  ############################
  # Client App + Dapr sidecar
  ############################
  client-app:
    environment:
      - DAPR_HTTP_PORT=3501
    build:
      context: .
      dockerfile: Client/Dockerfile
    ports:
      - "5112:5111"
      - "3501:3501"
    networks:
      - network
  client-dapr:
    image: "daprio/daprd:latest"
    command: ["./daprd",
    "-app-id", "client",
    "-app-port", "5111",
    "-dapr-http-port", "3501",
    "-dapr-grpc-port", "4002",
    "-log-level","debug"]
    depends_on:
      - client-app
    network_mode: "service:client-app"
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr:latest"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - network
  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    networks:
      - network
networks:
    network:
