apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsubrabbit
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: protocol
      value: amqp  
    - name: hostname
      value: rabbitmq
    - name: username
      value: elmerfud
    - name: password
      value: wabbit
    - name: durable
      value: false