apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: pubsub-subscriber-workflowTopic
spec:
  topic: workflowTopic
  routes: 
    default: /start
  pubsubname: kafka-pubsub
  deadLetterTopic: workflowTopic-DLQ
scopes:
- workflow-a
- workflow-b