apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: myresiliency
spec:
  policies:
    retries:
      pubsubRetry:
        policy: constant
        duration: 5s
        maxRetries: 3
  targets:
    components:
      kafka-pubsub:
        inbound:
          retry: pubsubRetry