apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore-pg
spec:
  type: state.postgresql
  version: v1
  metadata:
  # Connection string
  - name: connectionString
    value: "host=postgres-db user=postgres password=wO2VGDsMKR port=5432 database=postgres"
  # - name: actorStateStore
  #   value: "true"