apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: mydaprconfig
spec:
  metric:
    enabled: true
  metrics:
    enabled: true
  mtls:
    allowedClockSkew: 15m
    controlPlaneTrustDomain: cluster.local
    enabled: true
    sentryAddress: dapr-sentry.dapr-system.svc.cluster.local:443
    workloadCertTTL: 24h
  features:
    - name: SchedulerReminders
      enabled: true
