apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore-pg-v2
spec:
  type: state.postgresql
  version: v2
  metadata:
  # Connection string
  - name: connectionString
    value: "host=postgresql-1721406031.default.svc.cluster.local user=postgres password=v48ZCEMvx7 port=5432 database=postgres"
  - name: actorStateStore
    value: "true"
  - name: tablePrefix
    value: v2_